name: json_view
description: a simple json preview package that has a not bad performance. lazy load json tree node that cause less jank.
version: 0.0.2
homepage: https://github.com/laiiihz/json_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
